version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # -----------------------
    # .env 파일을 자동으로 읽어오도록 설정
    env_file:
      - .env
    # -----------------------
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - .:/app
      # -----------------------
      # secrets 폴더를 /app/secrets 에 마운트
      - ./secrets:/app/secrets
      # -----------------------

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
