# docker-compose.yml
# (주의) Docker Compose V2 이상에서 version은 필수가 아님. 없애도 됩니다.

version: '3.8'  # 경고가 뜨면 제거해도 동작은 합니다.

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # ----------------------------------------
    # (1) .env 파일 로드: 절대 경로 사용
    env_file:
      - /home/ec2-user/.env
    # ----------------------------------------
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    # ----------------------------------------
    # (2) volumes에 secrets 폴더 절대 경로 마운트
    #     + (기존) 현재 폴더(.)를 /app에 마운트
    volumes:
      - .:/app
      - /home/ec2-user/secrets:/app/secrets
    # ----------------------------------------

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
